import {
  cardIdSchema,
  cardOptionIdSchema,
  outcomeIdSchema,
  type Card,
  type CardCategory,
  type CardOption,
  type Outcome,
  type ResourceVector,
} from './contentTypes.ts'

const resources = (
  capital = 0,
  reputation = 0,
  innovation = 0,
): ResourceVector => ({ capital, reputation, innovation })

const outcome = (
  id: string,
  label: string,
  probability: number,
  effect: ResourceVector,
  explanation: string,
): Outcome => ({
  id: outcomeIdSchema.parse(id),
  label,
  probability,
  effect,
  explanation,
})

const option = (
  id: string,
  label: string,
  isDefault: boolean,
  cost: ResourceVector,
  outcomes: Outcome[],
): CardOption => ({
  id: cardOptionIdSchema.parse(id),
  label,
  isDefault,
  cost,
  outcomes,
})

const card = (
  id: string,
  category: CardCategory,
  title: string,
  scenario: string,
  learning: string,
  tags: string[],
  options: CardOption[],
): Card => ({
  id: cardIdSchema.parse(id),
  category,
  title,
  scenario,
  learning,
  tags,
  options,
})

export const cards: Card[] = [
  card(
    'decision-focus',
    'decision',
    'El primer enfoque',
    'Dos segmentos muestran interés, pero el equipo solo puede validar uno primero.',
    'Elegir un segmento concreto acelera el aprendizaje y evita repartir recursos escasos.',
    [],
    [
      option(
        'decision-focus-interviews',
        'Entrevistar a ambos segmentos',
        true,
        resources(),
        [
          outcome(
            'decision-focus-interviews-clear',
            'Patrón claro',
            65,
            resources(0, 1, 0),
            'Las entrevistas revelan una necesidad repetida y mejoran la credibilidad.',
          ),
          outcome(
            'decision-focus-interviews-noise',
            'Señales mezcladas',
            35,
            resources(0, 0, 1),
            'Las respuestas no coinciden, pero generan una nueva hipótesis para probar.',
          ),
        ],
      ),
      option(
        'decision-focus-campaign',
        'Probar una campaña pequeña',
        false,
        resources(500, 0, 0),
        [
          outcome(
            'decision-focus-campaign-fit',
            'Interés comprobado',
            55,
            resources(1500, 1, 0),
            'La respuesta pagada confirma demanda suficiente para concentrarse.',
          ),
          outcome(
            'decision-focus-campaign-weak',
            'Poca conversión',
            45,
            resources(0, 0, 1),
            'La campaña no vende, pero enseña qué mensaje necesita cambiar.',
          ),
        ],
      ),
    ],
  ),
  card(
    'decision-pricing',
    'decision',
    'Precio con propósito',
    'El prototipo gusta, pero todavía no sabes cuánto pagaría el cliente.',
    'Probar precios temprano transforma opiniones amables en evidencia de mercado.',
    [],
    [
      option(
        'decision-pricing-survey',
        'Hacer una encuesta de precio',
        true,
        resources(),
        [
          outcome(
            'decision-pricing-survey-range',
            'Rango útil',
            70,
            resources(0, 1, 0),
            'Las respuestas delimitan un rango que el equipo puede probar.',
          ),
          outcome(
            'decision-pricing-survey-bias',
            'Respuestas optimistas',
            30,
            resources(0, 0, 1),
            'La intención declarada no basta y obliga a diseñar una prueba real.',
          ),
        ],
      ),
      option(
        'decision-pricing-preorder',
        'Abrir una preventa',
        false,
        resources(500, 0, 0),
        [
          outcome(
            'decision-pricing-preorder-sales',
            'Primeras ventas',
            50,
            resources(2500, 1, 0),
            'Clientes reales aceptan el precio y financian el siguiente paso.',
          ),
          outcome(
            'decision-pricing-preorder-empty',
            'Carrito vacío',
            50,
            resources(0, -1, 1),
            'La oferta no convierte; la evidencia evita escalar un precio equivocado.',
          ),
        ],
      ),
    ],
  ),
  card(
    'decision-partner',
    'decision',
    'Socio estratégico',
    'Una organización ofrece acceso a clientes a cambio de exclusividad temporal.',
    'Una alianza debe evaluarse por aprendizaje, dependencia y opciones futuras, no solo por alcance inmediato.',
    [],
    [
      option(
        'decision-partner-pilot',
        'Proponer un piloto sin exclusividad',
        true,
        resources(),
        [
          outcome(
            'decision-partner-pilot-accepted',
            'Piloto aceptado',
            60,
            resources(500, 1, 0),
            'Un alcance limitado crea confianza sin cerrar otros canales.',
          ),
          outcome(
            'decision-partner-pilot-declined',
            'Oferta rechazada',
            40,
            resources(0, 0, 1),
            'Conservar independencia permite buscar una alianza mejor alineada.',
          ),
        ],
      ),
      option(
        'decision-partner-exclusive',
        'Aceptar la exclusividad',
        false,
        resources(500, 0, 0),
        [
          outcome(
            'decision-partner-exclusive-growth',
            'Canal acelerado',
            65,
            resources(2500, 1, 0),
            'El socio abre puertas y reduce el costo de adquirir clientes.',
          ),
          outcome(
            'decision-partner-exclusive-lock',
            'Dependencia costosa',
            35,
            resources(-500, -1, 0),
            'Las condiciones limitan al equipo y reducen su poder de negociación.',
          ),
        ],
      ),
    ],
  ),
  card(
    'decision-investor',
    'decision',
    'La oferta del inversionista',
    'Un inversionista ofrece capital, pero quiere acelerar antes de validar la retención.',
    'El capital amplifica una estrategia; no sustituye la evidencia de que el producto retiene clientes.',
    ['Inversionista'],
    [
      option(
        'decision-investor-delay',
        'Pedir tiempo para medir retención',
        true,
        resources(),
        [
          outcome(
            'decision-investor-delay-respect',
            'Disciplina valorada',
            55,
            resources(0, 1, 1),
            'La claridad de métricas fortalece la próxima conversación.',
          ),
          outcome(
            'decision-investor-delay-walks',
            'Oferta retirada',
            45,
            resources(0, 0, 1),
            'Perder una oferta evita crecer sin fundamentos y deja aprendizaje.',
          ),
        ],
      ),
      option(
        'decision-investor-accept',
        'Aceptar y acelerar',
        false,
        resources(0, 1, 0),
        [
          outcome(
            'decision-investor-accept-scale',
            'Escala saludable',
            45,
            resources(4000, 0, 1),
            'El equipo convierte la inversión en capacidad y aprendizaje.',
          ),
          outcome(
            'decision-investor-accept-burn',
            'Crecimiento frágil',
            55,
            resources(1500, -1, 0),
            'El gasto crece más rápido que la lealtad del cliente.',
          ),
        ],
      ),
    ],
  ),
  card(
    'decision-build-buy',
    'decision',
    'Construir o integrar',
    'Una función importante puede desarrollarse internamente o resolverse con un proveedor.',
    'La ventaja competitiva merece inversión propia; lo demás puede comprarse para aprender más rápido.',
    [],
    [
      option(
        'decision-build-buy-integrate',
        'Integrar una herramienta existente',
        true,
        resources(),
        [
          outcome(
            'decision-build-buy-integrate-fast',
            'Salida rápida',
            75,
            resources(500, 0, 1),
            'La integración libera tiempo para validar el valor principal.',
          ),
          outcome(
            'decision-build-buy-integrate-limit',
            'Límite técnico',
            25,
            resources(0, 0, 1),
            'La restricción aclara qué capacidad sí debe ser propia.',
          ),
        ],
      ),
      option(
        'decision-build-buy-build',
        'Construirla internamente',
        false,
        resources(1500, 0, 0),
        [
          outcome(
            'decision-build-buy-build-edge',
            'Ventaja diferenciadora',
            50,
            resources(1000, 0, 2),
            'La capacidad propia mejora el producto y crea conocimiento difícil de copiar.',
          ),
          outcome(
            'decision-build-buy-build-delay',
            'Entrega retrasada',
            50,
            resources(-500, -1, 1),
            'El esfuerzo técnico consume tiempo antes de comprobar el valor.',
          ),
        ],
      ),
    ],
  ),
  card(
    'decision-hire',
    'decision',
    'La primera contratación',
    'El equipo fundador necesita apoyo en ventas y producto al mismo tiempo.',
    'La primera contratación debe resolver el cuello de botella más crítico, no copiar un organigrama grande.',
    [],
    [
      option(
        'decision-hire-contract',
        'Contratar apoyo por proyecto',
        true,
        resources(),
        [
          outcome(
            'decision-hire-contract-flex',
            'Capacidad flexible',
            70,
            resources(500, 0, 1),
            'El apoyo puntual elimina el bloqueo sin aumentar costos fijos.',
          ),
          outcome(
            'decision-hire-contract-context',
            'Falta de contexto',
            30,
            resources(0, -1, 0),
            'La coordinación extra muestra qué conocimiento debe permanecer en el equipo.',
          ),
        ],
      ),
      option(
        'decision-hire-fulltime',
        'Incorporar a una persona clave',
        false,
        resources(2000, 0, 0),
        [
          outcome(
            'decision-hire-fulltime-leverage',
            'Equipo multiplicado',
            60,
            resources(1500, 1, 1),
            'La nueva persona entiende el problema y acelera ventas y aprendizaje.',
          ),
          outcome(
            'decision-hire-fulltime-mismatch',
            'Perfil desalineado',
            40,
            resources(-500, -1, 0),
            'Contratar antes de definir el rol genera costo y fricción.',
          ),
        ],
      ),
    ],
  ),
  card(
    'innovation-prototype',
    'innovation',
    'Prototipo en un día',
    'El equipo puede simular la experiencia antes de construir el producto completo.',
    'Un prototipo barato valida supuestos de uso antes de comprometer arquitectura y presupuesto.',
    [],
    [
      option(
        'innovation-prototype-paper',
        'Probar un prototipo de papel',
        true,
        resources(),
        [
          outcome(
            'innovation-prototype-paper-insight',
            'Flujo descubierto',
            80,
            resources(0, 0, 1),
            'Observar tareas revela dónde se confunden los usuarios.',
          ),
          outcome(
            'innovation-prototype-paper-flat',
            'Poca reacción',
            20,
            resources(0, 1, 0),
            'La conversación directa mejora la relación aunque el formato limite la prueba.',
          ),
        ],
      ),
      option(
        'innovation-prototype-code',
        'Construir una demo interactiva',
        false,
        resources(1000, 0, 0),
        [
          outcome(
            'innovation-prototype-code-wow',
            'Demostración convincente',
            60,
            resources(1000, 1, 2),
            'La interacción permite aprender y comunicar la visión.',
          ),
          outcome(
            'innovation-prototype-code-rework',
            'Código desechable',
            40,
            resources(-500, 0, 1),
            'Descartar una solución temprana evita mantener la opción equivocada.',
          ),
        ],
      ),
    ],
  ),
  card(
    'innovation-automation',
    'innovation',
    'Automatizar con criterio',
    'Una tarea manual consume tiempo, aunque todavía cambia cada semana.',
    'Automatizar un proceso inestable acelera el desorden; primero conviene entenderlo y simplificarlo.',
    [],
    [
      option(
        'innovation-automation-map',
        'Mapear y simplificar el proceso',
        true,
        resources(),
        [
          outcome(
            'innovation-automation-map-waste',
            'Paso innecesario',
            65,
            resources(500, 0, 1),
            'Eliminar trabajo aporta valor sin escribir código.',
          ),
          outcome(
            'innovation-automation-map-stable',
            'Proceso entendido',
            35,
            resources(0, 1, 1),
            'El mapa crea una base confiable para automatizar después.',
          ),
        ],
      ),
      option(
        'innovation-automation-build',
        'Automatizar de inmediato',
        false,
        resources(1000, 0, 0),
        [
          outcome(
            'innovation-automation-build-speed',
            'Capacidad liberada',
            50,
            resources(1000, 0, 2),
            'La automatización reduce tiempos y permite atender más clientes.',
          ),
          outcome(
            'innovation-automation-build-rework',
            'Reglas cambiantes',
            50,
            resources(-500, -1, 0),
            'El proceso cambia y obliga a rehacer una solución prematura.',
          ),
        ],
      ),
    ],
  ),
  card(
    'innovation-patent',
    'innovation',
    '¿Patentar o aprender?',
    'Una solución técnica parece novedosa, pero aún no tiene clientes recurrentes.',
    'La propiedad intelectual protege ventajas concretas; no reemplaza la validación de mercado.',
    ['Patente'],
    [
      option(
        'innovation-patent-document',
        'Documentar y seguir validando',
        true,
        resources(),
        [
          outcome(
            'innovation-patent-document-evidence',
            'Evidencia ordenada',
            75,
            resources(0, 0, 1),
            'El equipo conserva conocimiento mientras prioriza al cliente.',
          ),
          outcome(
            'innovation-patent-document-copy',
            'Aparece un imitador',
            25,
            resources(0, -1, 1),
            'La presión competitiva aclara qué parte debe diferenciarse.',
          ),
        ],
      ),
      option(
        'innovation-patent-file',
        'Iniciar una solicitud de patente',
        false,
        resources(2000, 0, 0),
        [
          outcome(
            'innovation-patent-file-signal',
            'Activo defendible',
            45,
            resources(1000, 1, 2),
            'La protección fortalece negociaciones y disciplina la documentación.',
          ),
          outcome(
            'innovation-patent-file-distraction',
            'Trámite prematuro',
            55,
            resources(-500, 0, 0),
            'El costo legal llega antes de comprobar que la invención crea valor.',
          ),
        ],
      ),
    ],
  ),
  card(
    'innovation-data',
    'innovation',
    'Una métrica que importa',
    'El tablero tiene muchos datos, pero nadie sabe cuál guía la siguiente decisión.',
    'Una métrica útil conecta comportamiento del cliente con valor, y conduce a una acción concreta.',
    [],
    [
      option(
        'innovation-data-question',
        'Elegir una pregunta crítica',
        true,
        resources(),
        [
          outcome(
            'innovation-data-question-focus',
            'Señal accionable',
            70,
            resources(0, 1, 1),
            'Una pregunta clara convierte datos dispersos en una decisión.',
          ),
          outcome(
            'innovation-data-question-gap',
            'Dato ausente',
            30,
            resources(0, 0, 1),
            'Descubrir el vacío permite instrumentar el siguiente experimento.',
          ),
        ],
      ),
      option(
        'innovation-data-dashboard',
        'Comprar una herramienta analítica',
        false,
        resources(1000, 0, 0),
        [
          outcome(
            'innovation-data-dashboard-visibility',
            'Patrón visible',
            55,
            resources(500, 0, 2),
            'La herramienta hace evidente un comportamiento valioso.',
          ),
          outcome(
            'innovation-data-dashboard-vanity',
            'Más métricas de vanidad',
            45,
            resources(-500, 0, 0),
            'La tecnología sin pregunta añade gráficos, no claridad.',
          ),
        ],
      ),
    ],
  ),
  card(
    'innovation-accessibility',
    'innovation',
    'Diseño para más personas',
    'Usuarios con distintas capacidades encuentran barreras en el prototipo.',
    'La accesibilidad mejora la experiencia general y amplía el mercado desde el diseño, no como parche final.',
    [],
    [
      option(
        'innovation-accessibility-audit',
        'Observar y registrar barreras',
        true,
        resources(),
        [
          outcome(
            'innovation-accessibility-audit-priority',
            'Prioridad clara',
            80,
            resources(0, 1, 1),
            'Las pruebas revelan cambios pequeños con gran impacto.',
          ),
          outcome(
            'innovation-accessibility-audit-scope',
            'Más trabajo del esperado',
            20,
            resources(0, 0, 1),
            'Conocer la deuda permite planificarla de forma responsable.',
          ),
        ],
      ),
      option(
        'innovation-accessibility-redesign',
        'Rediseñar el flujo principal',
        false,
        resources(1000, 0, 0),
        [
          outcome(
            'innovation-accessibility-redesign-reach',
            'Mercado ampliado',
            65,
            resources(1000, 2, 1),
            'Un flujo inclusivo mejora confianza y conversión.',
          ),
          outcome(
            'innovation-accessibility-redesign-delay',
            'Entrega aplazada',
            35,
            resources(-500, 1, 0),
            'El cambio toma tiempo, pero evita consolidar una barrera.',
          ),
        ],
      ),
    ],
  ),
  card(
    'innovation-pivot',
    'innovation',
    'Una tecnología, otro uso',
    'La solución no despega en su mercado inicial, pero otro sector pregunta por ella.',
    'Un pivote conserva aprendizajes y capacidades mientras cambia una hipótesis que la evidencia contradice.',
    [],
    [
      option(
        'innovation-pivot-interviews',
        'Investigar el nuevo sector',
        true,
        resources(),
        [
          outcome(
            'innovation-pivot-interviews-pull',
            'Demanda auténtica',
            60,
            resources(0, 1, 1),
            'Las conversaciones confirman un problema urgente y accesible.',
          ),
          outcome(
            'innovation-pivot-interviews-niche',
            'Interés aislado',
            40,
            resources(0, 0, 1),
            'El equipo evita confundir una solicitud con un mercado.',
          ),
        ],
      ),
      option(
        'innovation-pivot-demo',
        'Adaptar una demo especializada',
        false,
        resources(1500, 0, 0),
        [
          outcome(
            'innovation-pivot-demo-contract',
            'Nuevo contrato',
            45,
            resources(3000, 1, 2),
            'El uso alternativo convierte capacidad existente en valor.',
          ),
          outcome(
            'innovation-pivot-demo-miss',
            'Problema distinto',
            55,
            resources(-500, 0, 1),
            'La adaptación muestra que el sector necesita otra solución.',
          ),
        ],
      ),
    ],
  ),
  card(
    'opportunity-fair',
    'opportunity',
    'Feria empresarial',
    'Una feria reúne clientes, aliados e inversionistas durante un solo día.',
    'Un evento rinde más cuando el equipo define a quién quiere conocer y qué evidencia necesita obtener.',
    ['Feria empresarial'],
    [
      option(
        'opportunity-fair-network',
        'Asistir con reuniones agendadas',
        true,
        resources(),
        [
          outcome(
            'opportunity-fair-network-leads',
            'Contactos relevantes',
            70,
            resources(500, 1, 0),
            'La preparación convierte conversaciones en próximos pasos.',
          ),
          outcome(
            'opportunity-fair-network-learning',
            'Aprendizaje de mercado',
            30,
            resources(0, 0, 1),
            'Aunque no vende, el equipo regresa con objeciones reales.',
          ),
        ],
      ),
      option(
        'opportunity-fair-booth',
        'Contratar un puesto llamativo',
        false,
        resources(1500, 0, 0),
        [
          outcome(
            'opportunity-fair-booth-sales',
            'Gran visibilidad',
            55,
            resources(3000, 2, 0),
            'La demostración atrae público y genera oportunidades concretas.',
          ),
          outcome(
            'opportunity-fair-booth-traffic',
            'Mucho tráfico, pocos clientes',
            45,
            resources(-500, 0, 1),
            'La atención sin segmentación produce actividad, no resultados.',
          ),
        ],
      ),
    ],
  ),
  card(
    'opportunity-mentor',
    'opportunity',
    'Una mentoría inesperada',
    'Una persona experimentada ofrece revisar la estrategia durante una hora.',
    'La mentoría aporta preguntas y patrones; el equipo sigue siendo responsable de comprobar cada consejo.',
    [],
    [
      option(
        'opportunity-mentor-questions',
        'Llevar tres preguntas concretas',
        true,
        resources(),
        [
          outcome(
            'opportunity-mentor-questions-clarity',
            'Decisión desbloqueada',
            80,
            resources(0, 1, 1),
            'La preparación enfoca la conversación en el riesgo principal.',
          ),
          outcome(
            'opportunity-mentor-questions-challenge',
            'Supuesto cuestionado',
            20,
            resources(0, 0, 1),
            'Una pregunta difícil evita avanzar con una premisa débil.',
          ),
        ],
      ),
      option(
        'opportunity-mentor-retainer',
        'Contratar acompañamiento mensual',
        false,
        resources(1000, 0, 0),
        [
          outcome(
            'opportunity-mentor-retainer-network',
            'Red activada',
            60,
            resources(1500, 2, 0),
            'El seguimiento abre relaciones y refuerza la ejecución.',
          ),
          outcome(
            'opportunity-mentor-retainer-generic',
            'Consejo genérico',
            40,
            resources(-500, 0, 0),
            'Sin objetivos claros, más reuniones no producen más aprendizaje.',
          ),
        ],
      ),
    ],
  ),
  card(
    'opportunity-grant',
    'opportunity',
    'Convocatoria de capital semilla',
    'Un fondo ofrece recursos no reembolsables a proyectos con impacto medible.',
    'Las convocatorias son útiles cuando sus objetivos coinciden con la estrategia, no cuando desvían el producto.',
    [],
    [
      option(
        'opportunity-grant-check',
        'Revisar requisitos antes de aplicar',
        true,
        resources(),
        [
          outcome(
            'opportunity-grant-check-fit',
            'Alineación encontrada',
            55,
            resources(500, 1, 0),
            'La propuesta encaja y el equipo prepara evidencia relevante.',
          ),
          outcome(
            'opportunity-grant-check-skip',
            'No hay encaje',
            45,
            resources(0, 0, 1),
            'Decidir no aplicar protege tiempo para prioridades reales.',
          ),
        ],
      ),
      option(
        'opportunity-grant-apply',
        'Preparar la postulación completa',
        false,
        resources(500, 0, 0),
        [
          outcome(
            'opportunity-grant-apply-award',
            'Fondo adjudicado',
            35,
            resources(4000, 2, 0),
            'La evidencia de impacto consigue capital sin ceder propiedad.',
          ),
          outcome(
            'opportunity-grant-apply-feedback',
            'Propuesta no seleccionada',
            65,
            resources(0, 0, 1),
            'La retroalimentación fortalece la próxima medición de impacto.',
          ),
        ],
      ),
    ],
  ),
  card(
    'opportunity-referral',
    'opportunity',
    'Cliente que recomienda',
    'Una persona satisfecha ofrece presentar el producto a su red.',
    'Una recomendación funciona cuando es fácil explicar a quién ayuda el producto y por qué.',
    [],
    [
      option(
        'opportunity-referral-intro',
        'Pedir una presentación específica',
        true,
        resources(),
        [
          outcome(
            'opportunity-referral-intro-meeting',
            'Reunión calificada',
            75,
            resources(1000, 1, 0),
            'La confianza transferida reduce la fricción de una primera venta.',
          ),
          outcome(
            'opportunity-referral-intro-later',
            'Contacto para después',
            25,
            resources(0, 1, 0),
            'La relación crece aunque el momento de compra no sea ahora.',
          ),
        ],
      ),
      option(
        'opportunity-referral-program',
        'Lanzar un programa de referidos',
        false,
        resources(1000, 0, 0),
        [
          outcome(
            'opportunity-referral-program-loop',
            'Crecimiento repetible',
            50,
            resources(2500, 2, 0),
            'Un incentivo bien diseñado vuelve sistemática la recomendación.',
          ),
          outcome(
            'opportunity-referral-program-discount',
            'Solo atrae descuentos',
            50,
            resources(-500, 0, 1),
            'El incentivo equivocado trae volumen sin lealtad.',
          ),
        ],
      ),
    ],
  ),
  card(
    'opportunity-corporate',
    'opportunity',
    'Piloto corporativo',
    'Una empresa grande quiere probar la solución con un equipo pequeño.',
    'Un piloto debe tener alcance, responsable, métrica de éxito y decisión posterior definidos.',
    [],
    [
      option(
        'opportunity-corporate-scope',
        'Definir un piloto medible',
        true,
        resources(),
        [
          outcome(
            'opportunity-corporate-scope-approved',
            'Piloto aprobado',
            65,
            resources(1000, 1, 0),
            'El criterio de éxito alinea expectativas y acelera la decisión.',
          ),
          outcome(
            'opportunity-corporate-scope-stall',
            'Proceso lento',
            35,
            resources(0, 0, 1),
            'La demora revela quién debe patrocinar la prueba internamente.',
          ),
        ],
      ),
      option(
        'opportunity-corporate-custom',
        'Personalizar antes de acordar métricas',
        false,
        resources(1500, 0, 0),
        [
          outcome(
            'opportunity-corporate-custom-contract',
            'Contrato ampliado',
            45,
            resources(4000, 2, 0),
            'La adaptación demuestra valor y abre una cuenta importante.',
          ),
          outcome(
            'opportunity-corporate-custom-trap',
            'Trabajo sin decisión',
            55,
            resources(-500, -1, 1),
            'La personalización sin compromiso convierte al equipo en proveedor gratuito.',
          ),
        ],
      ),
    ],
  ),
  card(
    'opportunity-community',
    'opportunity',
    'Comunidad aliada',
    'Una comunidad profesional busca contenido práctico para sus miembros.',
    'Enseñar genera confianza cuando el contenido resuelve un problema real y no es solo publicidad.',
    [],
    [
      option(
        'opportunity-community-workshop',
        'Ofrecer un taller abierto',
        true,
        resources(),
        [
          outcome(
            'opportunity-community-workshop-trust',
            'Confianza ganada',
            70,
            resources(0, 2, 0),
            'Compartir conocimiento posiciona al equipo como aliado.',
          ),
          outcome(
            'opportunity-community-workshop-insight',
            'Nuevas preguntas',
            30,
            resources(0, 1, 1),
            'Las dudas del público revelan necesidades no atendidas.',
          ),
        ],
      ),
      option(
        'opportunity-community-sponsor',
        'Patrocinar el encuentro',
        false,
        resources(1000, 0, 0),
        [
          outcome(
            'opportunity-community-sponsor-leads',
            'Audiencia relevante',
            55,
            resources(1500, 2, 0),
            'La presencia de marca genera contactos con buen encaje.',
          ),
          outcome(
            'opportunity-community-sponsor-logo',
            'Solo aparece el logo',
            45,
            resources(-500, 0, 0),
            'Visibilidad sin participación difícilmente crea confianza.',
          ),
        ],
      ),
    ],
  ),
  card(
    'crisis-competitor',
    'crisis',
    'Competencia en movimiento',
    'Un competidor anuncia una función parecida y recibe mucha atención.',
    'La competencia confirma que existe un problema; responder bien exige volver al cliente y a la ventaja propia.',
    ['Competencia'],
    [
      option(
        'crisis-competitor-listen',
        'Hablar con clientes antes de reaccionar',
        true,
        resources(),
        [
          outcome(
            'crisis-competitor-listen-loyal',
            'Valor diferencial',
            70,
            resources(0, 1, 1),
            'Los clientes explican por qué permanecen y qué sí importa mejorar.',
          ),
          outcome(
            'crisis-competitor-listen-gap',
            'Brecha real',
            30,
            resources(0, -1, 1),
            'La comparación revela una debilidad concreta que atender.',
          ),
        ],
      ),
      option(
        'crisis-competitor-copy',
        'Copiar la función de inmediato',
        false,
        resources(1000, 0, 0),
        [
          outcome(
            'crisis-competitor-copy-parity',
            'Paridad rápida',
            40,
            resources(500, 0, 1),
            'La entrega reduce una objeción urgente.',
          ),
          outcome(
            'crisis-competitor-copy-chase',
            'Producto reactivo',
            60,
            resources(-500, -1, 0),
            'Perseguir al rival distrae de la propuesta propia.',
          ),
        ],
      ),
    ],
  ),
  card(
    'crisis-outage',
    'crisis',
    'Servicio interrumpido',
    'Una falla deja a varios clientes sin acceso durante una hora.',
    'En una crisis técnica, comunicar con claridad y aprender del incidente protege más confianza que ocultarlo.',
    [],
    [
      option(
        'crisis-outage-communicate',
        'Informar y publicar el aprendizaje',
        true,
        resources(),
        [
          outcome(
            'crisis-outage-communicate-trust',
            'Transparencia valorada',
            65,
            resources(0, 1, 1),
            'La respuesta clara demuestra responsabilidad.',
          ),
          outcome(
            'crisis-outage-communicate-churn',
            'Cliente impaciente',
            35,
            resources(-500, -1, 0),
            'Un cliente se va, pero el resto recibe información honesta.',
          ),
        ],
      ),
      option(
        'crisis-outage-redundancy',
        'Contratar infraestructura redundante',
        false,
        resources(1500, 0, 0),
        [
          outcome(
            'crisis-outage-redundancy-stable',
            'Servicio fortalecido',
            75,
            resources(500, 1, 1),
            'La inversión reduce el riesgo de repetir la falla.',
          ),
          outcome(
            'crisis-outage-redundancy-complex',
            'Configuración compleja',
            25,
            resources(-500, 0, 1),
            'La solución agrega aprendizaje y también costo operativo.',
          ),
        ],
      ),
    ],
  ),
  card(
    'crisis-cashflow',
    'crisis',
    'Cobro atrasado',
    'Un cliente importante demora el pago y compromete el flujo de caja.',
    'Facturar no es cobrar: condiciones, seguimiento y reservas convierten ventas en una operación sostenible.',
    [],
    [
      option(
        'crisis-cashflow-negotiate',
        'Negociar un calendario de pago',
        true,
        resources(),
        [
          outcome(
            'crisis-cashflow-negotiate-first',
            'Abono inmediato',
            60,
            resources(1000, 0, 0),
            'Un acuerdo concreto recupera parte del efectivo y preserva la relación.',
          ),
          outcome(
            'crisis-cashflow-negotiate-delay',
            'Nueva promesa',
            40,
            resources(-500, 0, 0),
            'La demora muestra que deben ajustarse las condiciones futuras.',
          ),
        ],
      ),
      option(
        'crisis-cashflow-credit',
        'Usar una línea de crédito',
        false,
        resources(500, 0, 0),
        [
          outcome(
            'crisis-cashflow-credit-bridge',
            'Operación protegida',
            65,
            resources(2000, 0, 0),
            'El puente evita detener trabajo mientras llega el cobro.',
          ),
          outcome(
            'crisis-cashflow-credit-cost',
            'Intereses acumulados',
            35,
            resources(500, -1, 0),
            'Resolver liquidez con deuda añade presión y exige mejor previsión.',
          ),
        ],
      ),
    ],
  ),
  card(
    'crisis-review',
    'crisis',
    'Reseña pública negativa',
    'Una experiencia deficiente aparece en redes y otros clientes comienzan a comentar.',
    'Responder una queja con empatía, hechos y corrección visible puede recuperar confianza.',
    [],
    [
      option(
        'crisis-review-respond',
        'Responder y corregir el problema',
        true,
        resources(),
        [
          outcome(
            'crisis-review-respond-recovery',
            'Cliente recuperado',
            70,
            resources(0, 1, 0),
            'La atención rápida convierte una falla en evidencia de compromiso.',
          ),
          outcome(
            'crisis-review-respond-pileon',
            'Más casos aparecen',
            30,
            resources(-500, -1, 1),
            'La conversación revela un patrón que el equipo debe corregir.',
          ),
        ],
      ),
      option(
        'crisis-review-campaign',
        'Lanzar una campaña de reputación',
        false,
        resources(1000, 0, 0),
        [
          outcome(
            'crisis-review-campaign-proof',
            'Historias positivas',
            45,
            resources(500, 2, 0),
            'Clientes satisfechos aportan evidencia equilibrada.',
          ),
          outcome(
            'crisis-review-campaign-backfire',
            'Respuesta percibida como evasiva',
            55,
            resources(-500, -1, 0),
            'Promocionar sin resolver la causa reduce la credibilidad.',
          ),
        ],
      ),
    ],
  ),
  card(
    'crisis-supplier',
    'crisis',
    'Proveedor inesperado',
    'El proveedor principal aumenta precios y reduce los plazos de soporte.',
    'La resiliencia operativa depende de conocer alternativas y evitar puntos únicos de falla.',
    [],
    [
      option(
        'crisis-supplier-negotiate',
        'Renegociar con datos de uso',
        true,
        resources(),
        [
          outcome(
            'crisis-supplier-negotiate-discount',
            'Acuerdo razonable',
            55,
            resources(500, 0, 0),
            'La información permite ajustar el contrato sin interrumpir el servicio.',
          ),
          outcome(
            'crisis-supplier-negotiate-no',
            'Condiciones firmes',
            45,
            resources(-500, 0, 1),
            'La negativa impulsa la búsqueda de una arquitectura menos dependiente.',
          ),
        ],
      ),
      option(
        'crisis-supplier-migrate',
        'Migrar a una alternativa',
        false,
        resources(1500, 0, 0),
        [
          outcome(
            'crisis-supplier-migrate-control',
            'Más control',
            55,
            resources(500, 0, 2),
            'La migración reduce costos futuros y concentra conocimiento.',
          ),
          outcome(
            'crisis-supplier-migrate-disruption',
            'Transición difícil',
            45,
            resources(-500, -1, 1),
            'Cambiar bajo presión expone dependencias que no estaban documentadas.',
          ),
        ],
      ),
    ],
  ),
  card(
    'crisis-team',
    'crisis',
    'Equipo al límite',
    'Las entregas urgentes se acumulan y el equipo empieza a cometer errores.',
    'La velocidad sostenible requiere priorizar, limitar trabajo en curso y cuidar la capacidad del equipo.',
    [],
    [
      option(
        'crisis-team-prioritize',
        'Reducir el alcance de la semana',
        true,
        resources(),
        [
          outcome(
            'crisis-team-prioritize-focus',
            'Foco recuperado',
            75,
            resources(0, 1, 1),
            'Terminar menos cosas importantes mejora calidad y ánimo.',
          ),
          outcome(
            'crisis-team-prioritize-delay',
            'Cliente inconforme',
            25,
            resources(-500, -1, 0),
            'Negociar una entrega cuesta reputación, pero evita una falla mayor.',
          ),
        ],
      ),
      option(
        'crisis-team-overtime',
        'Pagar apoyo y horas extra',
        false,
        resources(1500, 0, 0),
        [
          outcome(
            'crisis-team-overtime-delivery',
            'Entrega cumplida',
            50,
            resources(1000, 1, 0),
            'El esfuerzo puntual protege un compromiso crítico.',
          ),
          outcome(
            'crisis-team-overtime-burnout',
            'Agotamiento',
            50,
            resources(-500, -1, -1),
            'La presión sostenida reduce creatividad y aumenta errores.',
          ),
        ],
      ),
    ],
  ),
]
