import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { gameContent, validateGameContent } from '../src/domain/gameContent.ts'
import type { ResourceVector } from '../src/domain/contentTypes.ts'

const outputPath = resolve('supabase/seed.sql')
const quote = (value: string) => `'${value.replaceAll("'", "''")}'`
const boolean = (value: boolean) => (value ? 'true' : 'false')
const textArray = (values: string[]) =>
  values.length === 0
    ? `'{}'::text[]`
    : `array[${values.map(quote).join(', ')}]::text[]`
const resourceValues = ({
  capital,
  reputation,
  innovation,
}: ResourceVector) => [String(capital), String(reputation), String(innovation)]

const valuesBlock = (rows: string[][]) =>
  rows.map((row) => `  (${row.join(', ')})`).join(',\n')

const content = validateGameContent(gameContent)

const cardsSql = valuesBlock(
  content.cards.map((card) => [
    quote(card.id),
    `${quote(card.category)}::public.card_category`,
    quote(card.title),
    quote(card.scenario),
    quote(card.learning),
    textArray(card.tags),
  ]),
)

const options = content.cards.flatMap((card) =>
  card.options.map((option) => ({ cardId: card.id, ...option })),
)
const optionsSql = valuesBlock(
  options.map((option) => [
    quote(option.id),
    quote(option.cardId),
    quote(option.label),
    boolean(option.isDefault),
    ...resourceValues(option.cost),
  ]),
)

const outcomes = options.flatMap((option) =>
  option.outcomes.map((outcome) => ({ optionId: option.id, ...outcome })),
)
const outcomesSql = valuesBlock(
  outcomes.map((outcome) => [
    quote(outcome.id),
    quote(outcome.optionId),
    quote(outcome.label),
    String(outcome.probability),
    ...resourceValues(outcome.effect),
    quote(outcome.explanation),
  ]),
)

const boardSql = valuesBlock(
  content.board.map((space) => [
    String(space.position),
    `${quote(space.stage)}::public.board_stage`,
    space.category ? `${quote(space.category)}::public.card_category` : 'null',
    space.cardId ? quote(space.cardId) : 'null',
  ]),
)

const managementSql = valuesBlock(
  content.managementActions.map((action) => [
    quote(action.id),
    quote(action.label),
    ...resourceValues(action.cost),
    ...resourceValues(action.effect),
    quote(action.explanation),
  ]),
)

const sql = `-- Generated by scripts/generateSeed.ts. Do not edit by hand.
begin;

insert into public.cards (id, category, title, scenario, learning, tags) values
${cardsSql}
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  scenario = excluded.scenario,
  learning = excluded.learning,
  tags = excluded.tags;

insert into public.card_options (
  id, card_id, label, is_default, cost_capital, cost_reputation, cost_innovation
) values
${optionsSql}
on conflict (id) do update set
  card_id = excluded.card_id,
  label = excluded.label,
  is_default = excluded.is_default,
  cost_capital = excluded.cost_capital,
  cost_reputation = excluded.cost_reputation,
  cost_innovation = excluded.cost_innovation;

insert into public.card_outcomes (
  id, option_id, label, probability, capital_delta, reputation_delta,
  innovation_delta, explanation
) values
${outcomesSql}
on conflict (id) do update set
  option_id = excluded.option_id,
  label = excluded.label,
  probability = excluded.probability,
  capital_delta = excluded.capital_delta,
  reputation_delta = excluded.reputation_delta,
  innovation_delta = excluded.innovation_delta,
  explanation = excluded.explanation;

insert into public.board_spaces (position, stage, category, card_id) values
${boardSql}
on conflict (position) do update set
  stage = excluded.stage,
  category = excluded.category,
  card_id = excluded.card_id;

insert into public.management_actions (
  id, label, cost_capital, cost_reputation, cost_innovation, capital_delta,
  reputation_delta, innovation_delta, explanation
) values
${managementSql}
on conflict (id) do update set
  label = excluded.label,
  cost_capital = excluded.cost_capital,
  cost_reputation = excluded.cost_reputation,
  cost_innovation = excluded.cost_innovation,
  capital_delta = excluded.capital_delta,
  reputation_delta = excluded.reputation_delta,
  innovation_delta = excluded.innovation_delta,
  explanation = excluded.explanation;

commit;
`

if (process.argv.includes('--write')) {
  writeFileSync(outputPath, sql)
} else if (process.argv.includes('--check')) {
  const existing = readFileSync(outputPath, 'utf8')
  if (existing !== sql) {
    throw new Error('supabase/seed.sql is stale; run pnpm content:seed')
  }
} else {
  process.stdout.write(sql)
}
