-- Initial canonical game content, snapshot of generated seed.sql.
-- Future content changes require a new migration.

insert into public.cards (id, category, title, scenario, learning, tags) values
  ('decision-focus', 'decision'::public.card_category, 'El primer enfoque', 'Dos segmentos muestran interés, pero el equipo solo puede validar uno primero.', 'Elegir un segmento concreto acelera el aprendizaje y evita repartir recursos escasos.', '{}'::text[]),
  ('decision-pricing', 'decision'::public.card_category, 'Precio con propósito', 'El prototipo gusta, pero todavía no sabes cuánto pagaría el cliente.', 'Probar precios temprano transforma opiniones amables en evidencia de mercado.', '{}'::text[]),
  ('decision-partner', 'decision'::public.card_category, 'Socio estratégico', 'Una organización ofrece acceso a clientes a cambio de exclusividad temporal.', 'Una alianza debe evaluarse por aprendizaje, dependencia y opciones futuras, no solo por alcance inmediato.', '{}'::text[]),
  ('decision-investor', 'decision'::public.card_category, 'La oferta del inversionista', 'Un inversionista ofrece capital, pero quiere acelerar antes de validar la retención.', 'El capital amplifica una estrategia; no sustituye la evidencia de que el producto retiene clientes.', array['Inversionista']::text[]),
  ('decision-build-buy', 'decision'::public.card_category, 'Construir o integrar', 'Una función importante puede desarrollarse internamente o resolverse con un proveedor.', 'La ventaja competitiva merece inversión propia; lo demás puede comprarse para aprender más rápido.', '{}'::text[]),
  ('decision-hire', 'decision'::public.card_category, 'La primera contratación', 'El equipo fundador necesita apoyo en ventas y producto al mismo tiempo.', 'La primera contratación debe resolver el cuello de botella más crítico, no copiar un organigrama grande.', '{}'::text[]),
  ('innovation-prototype', 'innovation'::public.card_category, 'Prototipo en un día', 'El equipo puede simular la experiencia antes de construir el producto completo.', 'Un prototipo barato valida supuestos de uso antes de comprometer arquitectura y presupuesto.', '{}'::text[]),
  ('innovation-automation', 'innovation'::public.card_category, 'Automatizar con criterio', 'Una tarea manual consume tiempo, aunque todavía cambia cada semana.', 'Automatizar un proceso inestable acelera el desorden; primero conviene entenderlo y simplificarlo.', '{}'::text[]),
  ('innovation-patent', 'innovation'::public.card_category, '¿Patentar o aprender?', 'Una solución técnica parece novedosa, pero aún no tiene clientes recurrentes.', 'La propiedad intelectual protege ventajas concretas; no reemplaza la validación de mercado.', array['Patente']::text[]),
  ('innovation-data', 'innovation'::public.card_category, 'Una métrica que importa', 'El tablero tiene muchos datos, pero nadie sabe cuál guía la siguiente decisión.', 'Una métrica útil conecta comportamiento del cliente con valor, y conduce a una acción concreta.', '{}'::text[]),
  ('innovation-accessibility', 'innovation'::public.card_category, 'Diseño para más personas', 'Usuarios con distintas capacidades encuentran barreras en el prototipo.', 'La accesibilidad mejora la experiencia general y amplía el mercado desde el diseño, no como parche final.', '{}'::text[]),
  ('innovation-pivot', 'innovation'::public.card_category, 'Una tecnología, otro uso', 'La solución no despega en su mercado inicial, pero otro sector pregunta por ella.', 'Un pivote conserva aprendizajes y capacidades mientras cambia una hipótesis que la evidencia contradice.', '{}'::text[]),
  ('opportunity-fair', 'opportunity'::public.card_category, 'Feria empresarial', 'Una feria reúne clientes, aliados e inversionistas durante un solo día.', 'Un evento rinde más cuando el equipo define a quién quiere conocer y qué evidencia necesita obtener.', array['Feria empresarial']::text[]),
  ('opportunity-mentor', 'opportunity'::public.card_category, 'Una mentoría inesperada', 'Una persona experimentada ofrece revisar la estrategia durante una hora.', 'La mentoría aporta preguntas y patrones; el equipo sigue siendo responsable de comprobar cada consejo.', '{}'::text[]),
  ('opportunity-grant', 'opportunity'::public.card_category, 'Convocatoria de capital semilla', 'Un fondo ofrece recursos no reembolsables a proyectos con impacto medible.', 'Las convocatorias son útiles cuando sus objetivos coinciden con la estrategia, no cuando desvían el producto.', '{}'::text[]),
  ('opportunity-referral', 'opportunity'::public.card_category, 'Cliente que recomienda', 'Una persona satisfecha ofrece presentar el producto a su red.', 'Una recomendación funciona cuando es fácil explicar a quién ayuda el producto y por qué.', '{}'::text[]),
  ('opportunity-corporate', 'opportunity'::public.card_category, 'Piloto corporativo', 'Una empresa grande quiere probar la solución con un equipo pequeño.', 'Un piloto debe tener alcance, responsable, métrica de éxito y decisión posterior definidos.', '{}'::text[]),
  ('opportunity-community', 'opportunity'::public.card_category, 'Comunidad aliada', 'Una comunidad profesional busca contenido práctico para sus miembros.', 'Enseñar genera confianza cuando el contenido resuelve un problema real y no es solo publicidad.', '{}'::text[]),
  ('crisis-competitor', 'crisis'::public.card_category, 'Competencia en movimiento', 'Un competidor anuncia una función parecida y recibe mucha atención.', 'La competencia confirma que existe un problema; responder bien exige volver al cliente y a la ventaja propia.', array['Competencia']::text[]),
  ('crisis-outage', 'crisis'::public.card_category, 'Servicio interrumpido', 'Una falla deja a varios clientes sin acceso durante una hora.', 'En una crisis técnica, comunicar con claridad y aprender del incidente protege más confianza que ocultarlo.', '{}'::text[]),
  ('crisis-cashflow', 'crisis'::public.card_category, 'Cobro atrasado', 'Un cliente importante demora el pago y compromete el flujo de caja.', 'Facturar no es cobrar: condiciones, seguimiento y reservas convierten ventas en una operación sostenible.', '{}'::text[]),
  ('crisis-review', 'crisis'::public.card_category, 'Reseña pública negativa', 'Una experiencia deficiente aparece en redes y otros clientes comienzan a comentar.', 'Responder una queja con empatía, hechos y corrección visible puede recuperar confianza.', '{}'::text[]),
  ('crisis-supplier', 'crisis'::public.card_category, 'Proveedor inesperado', 'El proveedor principal aumenta precios y reduce los plazos de soporte.', 'La resiliencia operativa depende de conocer alternativas y evitar puntos únicos de falla.', '{}'::text[]),
  ('crisis-team', 'crisis'::public.card_category, 'Equipo al límite', 'Las entregas urgentes se acumulan y el equipo empieza a cometer errores.', 'La velocidad sostenible requiere priorizar, limitar trabajo en curso y cuidar la capacidad del equipo.', '{}'::text[])
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  scenario = excluded.scenario,
  learning = excluded.learning,
  tags = excluded.tags;

insert into public.card_options (
  id, card_id, label, is_default, cost_capital, cost_reputation, cost_innovation
) values
  ('decision-focus-interviews', 'decision-focus', 'Entrevistar a ambos segmentos', true, 0, 0, 0),
  ('decision-focus-campaign', 'decision-focus', 'Probar una campaña pequeña', false, 500, 0, 0),
  ('decision-pricing-survey', 'decision-pricing', 'Hacer una encuesta de precio', true, 0, 0, 0),
  ('decision-pricing-preorder', 'decision-pricing', 'Abrir una preventa', false, 500, 0, 0),
  ('decision-partner-pilot', 'decision-partner', 'Proponer un piloto sin exclusividad', true, 0, 0, 0),
  ('decision-partner-exclusive', 'decision-partner', 'Aceptar la exclusividad', false, 500, 0, 0),
  ('decision-investor-delay', 'decision-investor', 'Pedir tiempo para medir retención', true, 0, 0, 0),
  ('decision-investor-accept', 'decision-investor', 'Aceptar y acelerar', false, 0, 1, 0),
  ('decision-build-buy-integrate', 'decision-build-buy', 'Integrar una herramienta existente', true, 0, 0, 0),
  ('decision-build-buy-build', 'decision-build-buy', 'Construirla internamente', false, 1500, 0, 0),
  ('decision-hire-contract', 'decision-hire', 'Contratar apoyo por proyecto', true, 0, 0, 0),
  ('decision-hire-fulltime', 'decision-hire', 'Incorporar a una persona clave', false, 2000, 0, 0),
  ('innovation-prototype-paper', 'innovation-prototype', 'Probar un prototipo de papel', true, 0, 0, 0),
  ('innovation-prototype-code', 'innovation-prototype', 'Construir una demo interactiva', false, 1000, 0, 0),
  ('innovation-automation-map', 'innovation-automation', 'Mapear y simplificar el proceso', true, 0, 0, 0),
  ('innovation-automation-build', 'innovation-automation', 'Automatizar de inmediato', false, 1000, 0, 0),
  ('innovation-patent-document', 'innovation-patent', 'Documentar y seguir validando', true, 0, 0, 0),
  ('innovation-patent-file', 'innovation-patent', 'Iniciar una solicitud de patente', false, 2000, 0, 0),
  ('innovation-data-question', 'innovation-data', 'Elegir una pregunta crítica', true, 0, 0, 0),
  ('innovation-data-dashboard', 'innovation-data', 'Comprar una herramienta analítica', false, 1000, 0, 0),
  ('innovation-accessibility-audit', 'innovation-accessibility', 'Observar y registrar barreras', true, 0, 0, 0),
  ('innovation-accessibility-redesign', 'innovation-accessibility', 'Rediseñar el flujo principal', false, 1000, 0, 0),
  ('innovation-pivot-interviews', 'innovation-pivot', 'Investigar el nuevo sector', true, 0, 0, 0),
  ('innovation-pivot-demo', 'innovation-pivot', 'Adaptar una demo especializada', false, 1500, 0, 0),
  ('opportunity-fair-network', 'opportunity-fair', 'Asistir con reuniones agendadas', true, 0, 0, 0),
  ('opportunity-fair-booth', 'opportunity-fair', 'Contratar un puesto llamativo', false, 1500, 0, 0),
  ('opportunity-mentor-questions', 'opportunity-mentor', 'Llevar tres preguntas concretas', true, 0, 0, 0),
  ('opportunity-mentor-retainer', 'opportunity-mentor', 'Contratar acompañamiento mensual', false, 1000, 0, 0),
  ('opportunity-grant-check', 'opportunity-grant', 'Revisar requisitos antes de aplicar', true, 0, 0, 0),
  ('opportunity-grant-apply', 'opportunity-grant', 'Preparar la postulación completa', false, 500, 0, 0),
  ('opportunity-referral-intro', 'opportunity-referral', 'Pedir una presentación específica', true, 0, 0, 0),
  ('opportunity-referral-program', 'opportunity-referral', 'Lanzar un programa de referidos', false, 1000, 0, 0),
  ('opportunity-corporate-scope', 'opportunity-corporate', 'Definir un piloto medible', true, 0, 0, 0),
  ('opportunity-corporate-custom', 'opportunity-corporate', 'Personalizar antes de acordar métricas', false, 1500, 0, 0),
  ('opportunity-community-workshop', 'opportunity-community', 'Ofrecer un taller abierto', true, 0, 0, 0),
  ('opportunity-community-sponsor', 'opportunity-community', 'Patrocinar el encuentro', false, 1000, 0, 0),
  ('crisis-competitor-listen', 'crisis-competitor', 'Hablar con clientes antes de reaccionar', true, 0, 0, 0),
  ('crisis-competitor-copy', 'crisis-competitor', 'Copiar la función de inmediato', false, 1000, 0, 0),
  ('crisis-outage-communicate', 'crisis-outage', 'Informar y publicar el aprendizaje', true, 0, 0, 0),
  ('crisis-outage-redundancy', 'crisis-outage', 'Contratar infraestructura redundante', false, 1500, 0, 0),
  ('crisis-cashflow-negotiate', 'crisis-cashflow', 'Negociar un calendario de pago', true, 0, 0, 0),
  ('crisis-cashflow-credit', 'crisis-cashflow', 'Usar una línea de crédito', false, 500, 0, 0),
  ('crisis-review-respond', 'crisis-review', 'Responder y corregir el problema', true, 0, 0, 0),
  ('crisis-review-campaign', 'crisis-review', 'Lanzar una campaña de reputación', false, 1000, 0, 0),
  ('crisis-supplier-negotiate', 'crisis-supplier', 'Renegociar con datos de uso', true, 0, 0, 0),
  ('crisis-supplier-migrate', 'crisis-supplier', 'Migrar a una alternativa', false, 1500, 0, 0),
  ('crisis-team-prioritize', 'crisis-team', 'Reducir el alcance de la semana', true, 0, 0, 0),
  ('crisis-team-overtime', 'crisis-team', 'Pagar apoyo y horas extra', false, 1500, 0, 0)
on conflict (id) do update set
  card_id = excluded.card_id,
  label = excluded.label,
  is_default = excluded.is_default,
  cost_capital = excluded.cost_capital,
  cost_reputation = excluded.cost_reputation,
  cost_innovation = excluded.cost_innovation;

insert into public.card_outcomes (
  id, option_id, label, probability, capital_delta, reputation_delta,
  innovation_delta, explanation
) values
  ('decision-focus-interviews-clear', 'decision-focus-interviews', 'Patrón claro', 65, 0, 1, 0, 'Las entrevistas revelan una necesidad repetida y mejoran la credibilidad.'),
  ('decision-focus-interviews-noise', 'decision-focus-interviews', 'Señales mezcladas', 35, 0, 0, 1, 'Las respuestas no coinciden, pero generan una nueva hipótesis para probar.'),
  ('decision-focus-campaign-fit', 'decision-focus-campaign', 'Interés comprobado', 55, 1500, 1, 0, 'La respuesta pagada confirma demanda suficiente para concentrarse.'),
  ('decision-focus-campaign-weak', 'decision-focus-campaign', 'Poca conversión', 45, 0, 0, 1, 'La campaña no vende, pero enseña qué mensaje necesita cambiar.'),
  ('decision-pricing-survey-range', 'decision-pricing-survey', 'Rango útil', 70, 0, 1, 0, 'Las respuestas delimitan un rango que el equipo puede probar.'),
  ('decision-pricing-survey-bias', 'decision-pricing-survey', 'Respuestas optimistas', 30, 0, 0, 1, 'La intención declarada no basta y obliga a diseñar una prueba real.'),
  ('decision-pricing-preorder-sales', 'decision-pricing-preorder', 'Primeras ventas', 50, 2500, 1, 0, 'Clientes reales aceptan el precio y financian el siguiente paso.'),
  ('decision-pricing-preorder-empty', 'decision-pricing-preorder', 'Carrito vacío', 50, 0, -1, 1, 'La oferta no convierte; la evidencia evita escalar un precio equivocado.'),
  ('decision-partner-pilot-accepted', 'decision-partner-pilot', 'Piloto aceptado', 60, 500, 1, 0, 'Un alcance limitado crea confianza sin cerrar otros canales.'),
  ('decision-partner-pilot-declined', 'decision-partner-pilot', 'Oferta rechazada', 40, 0, 0, 1, 'Conservar independencia permite buscar una alianza mejor alineada.'),
  ('decision-partner-exclusive-growth', 'decision-partner-exclusive', 'Canal acelerado', 65, 2500, 1, 0, 'El socio abre puertas y reduce el costo de adquirir clientes.'),
  ('decision-partner-exclusive-lock', 'decision-partner-exclusive', 'Dependencia costosa', 35, -500, -1, 0, 'Las condiciones limitan al equipo y reducen su poder de negociación.'),
  ('decision-investor-delay-respect', 'decision-investor-delay', 'Disciplina valorada', 55, 0, 1, 1, 'La claridad de métricas fortalece la próxima conversación.'),
  ('decision-investor-delay-walks', 'decision-investor-delay', 'Oferta retirada', 45, 0, 0, 1, 'Perder una oferta evita crecer sin fundamentos y deja aprendizaje.'),
  ('decision-investor-accept-scale', 'decision-investor-accept', 'Escala saludable', 45, 4000, 0, 1, 'El equipo convierte la inversión en capacidad y aprendizaje.'),
  ('decision-investor-accept-burn', 'decision-investor-accept', 'Crecimiento frágil', 55, 1500, -1, 0, 'El gasto crece más rápido que la lealtad del cliente.'),
  ('decision-build-buy-integrate-fast', 'decision-build-buy-integrate', 'Salida rápida', 75, 500, 0, 1, 'La integración libera tiempo para validar el valor principal.'),
  ('decision-build-buy-integrate-limit', 'decision-build-buy-integrate', 'Límite técnico', 25, 0, 0, 1, 'La restricción aclara qué capacidad sí debe ser propia.'),
  ('decision-build-buy-build-edge', 'decision-build-buy-build', 'Ventaja diferenciadora', 50, 1000, 0, 2, 'La capacidad propia mejora el producto y crea conocimiento difícil de copiar.'),
  ('decision-build-buy-build-delay', 'decision-build-buy-build', 'Entrega retrasada', 50, -500, -1, 1, 'El esfuerzo técnico consume tiempo antes de comprobar el valor.'),
  ('decision-hire-contract-flex', 'decision-hire-contract', 'Capacidad flexible', 70, 500, 0, 1, 'El apoyo puntual elimina el bloqueo sin aumentar costos fijos.'),
  ('decision-hire-contract-context', 'decision-hire-contract', 'Falta de contexto', 30, 0, -1, 0, 'La coordinación extra muestra qué conocimiento debe permanecer en el equipo.'),
  ('decision-hire-fulltime-leverage', 'decision-hire-fulltime', 'Equipo multiplicado', 60, 1500, 1, 1, 'La nueva persona entiende el problema y acelera ventas y aprendizaje.'),
  ('decision-hire-fulltime-mismatch', 'decision-hire-fulltime', 'Perfil desalineado', 40, -500, -1, 0, 'Contratar antes de definir el rol genera costo y fricción.'),
  ('innovation-prototype-paper-insight', 'innovation-prototype-paper', 'Flujo descubierto', 80, 0, 0, 1, 'Observar tareas revela dónde se confunden los usuarios.'),
  ('innovation-prototype-paper-flat', 'innovation-prototype-paper', 'Poca reacción', 20, 0, 1, 0, 'La conversación directa mejora la relación aunque el formato limite la prueba.'),
  ('innovation-prototype-code-wow', 'innovation-prototype-code', 'Demostración convincente', 60, 1000, 1, 2, 'La interacción permite aprender y comunicar la visión.'),
  ('innovation-prototype-code-rework', 'innovation-prototype-code', 'Código desechable', 40, -500, 0, 1, 'Descartar una solución temprana evita mantener la opción equivocada.'),
  ('innovation-automation-map-waste', 'innovation-automation-map', 'Paso innecesario', 65, 500, 0, 1, 'Eliminar trabajo aporta valor sin escribir código.'),
  ('innovation-automation-map-stable', 'innovation-automation-map', 'Proceso entendido', 35, 0, 1, 1, 'El mapa crea una base confiable para automatizar después.'),
  ('innovation-automation-build-speed', 'innovation-automation-build', 'Capacidad liberada', 50, 1000, 0, 2, 'La automatización reduce tiempos y permite atender más clientes.'),
  ('innovation-automation-build-rework', 'innovation-automation-build', 'Reglas cambiantes', 50, -500, -1, 0, 'El proceso cambia y obliga a rehacer una solución prematura.'),
  ('innovation-patent-document-evidence', 'innovation-patent-document', 'Evidencia ordenada', 75, 0, 0, 1, 'El equipo conserva conocimiento mientras prioriza al cliente.'),
  ('innovation-patent-document-copy', 'innovation-patent-document', 'Aparece un imitador', 25, 0, -1, 1, 'La presión competitiva aclara qué parte debe diferenciarse.'),
  ('innovation-patent-file-signal', 'innovation-patent-file', 'Activo defendible', 45, 1000, 1, 2, 'La protección fortalece negociaciones y disciplina la documentación.'),
  ('innovation-patent-file-distraction', 'innovation-patent-file', 'Trámite prematuro', 55, -500, 0, 0, 'El costo legal llega antes de comprobar que la invención crea valor.'),
  ('innovation-data-question-focus', 'innovation-data-question', 'Señal accionable', 70, 0, 1, 1, 'Una pregunta clara convierte datos dispersos en una decisión.'),
  ('innovation-data-question-gap', 'innovation-data-question', 'Dato ausente', 30, 0, 0, 1, 'Descubrir el vacío permite instrumentar el siguiente experimento.'),
  ('innovation-data-dashboard-visibility', 'innovation-data-dashboard', 'Patrón visible', 55, 500, 0, 2, 'La herramienta hace evidente un comportamiento valioso.'),
  ('innovation-data-dashboard-vanity', 'innovation-data-dashboard', 'Más métricas de vanidad', 45, -500, 0, 0, 'La tecnología sin pregunta añade gráficos, no claridad.'),
  ('innovation-accessibility-audit-priority', 'innovation-accessibility-audit', 'Prioridad clara', 80, 0, 1, 1, 'Las pruebas revelan cambios pequeños con gran impacto.'),
  ('innovation-accessibility-audit-scope', 'innovation-accessibility-audit', 'Más trabajo del esperado', 20, 0, 0, 1, 'Conocer la deuda permite planificarla de forma responsable.'),
  ('innovation-accessibility-redesign-reach', 'innovation-accessibility-redesign', 'Mercado ampliado', 65, 1000, 2, 1, 'Un flujo inclusivo mejora confianza y conversión.'),
  ('innovation-accessibility-redesign-delay', 'innovation-accessibility-redesign', 'Entrega aplazada', 35, -500, 1, 0, 'El cambio toma tiempo, pero evita consolidar una barrera.'),
  ('innovation-pivot-interviews-pull', 'innovation-pivot-interviews', 'Demanda auténtica', 60, 0, 1, 1, 'Las conversaciones confirman un problema urgente y accesible.'),
  ('innovation-pivot-interviews-niche', 'innovation-pivot-interviews', 'Interés aislado', 40, 0, 0, 1, 'El equipo evita confundir una solicitud con un mercado.'),
  ('innovation-pivot-demo-contract', 'innovation-pivot-demo', 'Nuevo contrato', 45, 3000, 1, 2, 'El uso alternativo convierte capacidad existente en valor.'),
  ('innovation-pivot-demo-miss', 'innovation-pivot-demo', 'Problema distinto', 55, -500, 0, 1, 'La adaptación muestra que el sector necesita otra solución.'),
  ('opportunity-fair-network-leads', 'opportunity-fair-network', 'Contactos relevantes', 70, 500, 1, 0, 'La preparación convierte conversaciones en próximos pasos.'),
  ('opportunity-fair-network-learning', 'opportunity-fair-network', 'Aprendizaje de mercado', 30, 0, 0, 1, 'Aunque no vende, el equipo regresa con objeciones reales.'),
  ('opportunity-fair-booth-sales', 'opportunity-fair-booth', 'Gran visibilidad', 55, 3000, 2, 0, 'La demostración atrae público y genera oportunidades concretas.'),
  ('opportunity-fair-booth-traffic', 'opportunity-fair-booth', 'Mucho tráfico, pocos clientes', 45, -500, 0, 1, 'La atención sin segmentación produce actividad, no resultados.'),
  ('opportunity-mentor-questions-clarity', 'opportunity-mentor-questions', 'Decisión desbloqueada', 80, 0, 1, 1, 'La preparación enfoca la conversación en el riesgo principal.'),
  ('opportunity-mentor-questions-challenge', 'opportunity-mentor-questions', 'Supuesto cuestionado', 20, 0, 0, 1, 'Una pregunta difícil evita avanzar con una premisa débil.'),
  ('opportunity-mentor-retainer-network', 'opportunity-mentor-retainer', 'Red activada', 60, 1500, 2, 0, 'El seguimiento abre relaciones y refuerza la ejecución.'),
  ('opportunity-mentor-retainer-generic', 'opportunity-mentor-retainer', 'Consejo genérico', 40, -500, 0, 0, 'Sin objetivos claros, más reuniones no producen más aprendizaje.'),
  ('opportunity-grant-check-fit', 'opportunity-grant-check', 'Alineación encontrada', 55, 500, 1, 0, 'La propuesta encaja y el equipo prepara evidencia relevante.'),
  ('opportunity-grant-check-skip', 'opportunity-grant-check', 'No hay encaje', 45, 0, 0, 1, 'Decidir no aplicar protege tiempo para prioridades reales.'),
  ('opportunity-grant-apply-award', 'opportunity-grant-apply', 'Fondo adjudicado', 35, 4000, 2, 0, 'La evidencia de impacto consigue capital sin ceder propiedad.'),
  ('opportunity-grant-apply-feedback', 'opportunity-grant-apply', 'Propuesta no seleccionada', 65, 0, 0, 1, 'La retroalimentación fortalece la próxima medición de impacto.'),
  ('opportunity-referral-intro-meeting', 'opportunity-referral-intro', 'Reunión calificada', 75, 1000, 1, 0, 'La confianza transferida reduce la fricción de una primera venta.'),
  ('opportunity-referral-intro-later', 'opportunity-referral-intro', 'Contacto para después', 25, 0, 1, 0, 'La relación crece aunque el momento de compra no sea ahora.'),
  ('opportunity-referral-program-loop', 'opportunity-referral-program', 'Crecimiento repetible', 50, 2500, 2, 0, 'Un incentivo bien diseñado vuelve sistemática la recomendación.'),
  ('opportunity-referral-program-discount', 'opportunity-referral-program', 'Solo atrae descuentos', 50, -500, 0, 1, 'El incentivo equivocado trae volumen sin lealtad.'),
  ('opportunity-corporate-scope-approved', 'opportunity-corporate-scope', 'Piloto aprobado', 65, 1000, 1, 0, 'El criterio de éxito alinea expectativas y acelera la decisión.'),
  ('opportunity-corporate-scope-stall', 'opportunity-corporate-scope', 'Proceso lento', 35, 0, 0, 1, 'La demora revela quién debe patrocinar la prueba internamente.'),
  ('opportunity-corporate-custom-contract', 'opportunity-corporate-custom', 'Contrato ampliado', 45, 4000, 2, 0, 'La adaptación demuestra valor y abre una cuenta importante.'),
  ('opportunity-corporate-custom-trap', 'opportunity-corporate-custom', 'Trabajo sin decisión', 55, -500, -1, 1, 'La personalización sin compromiso convierte al equipo en proveedor gratuito.'),
  ('opportunity-community-workshop-trust', 'opportunity-community-workshop', 'Confianza ganada', 70, 0, 2, 0, 'Compartir conocimiento posiciona al equipo como aliado.'),
  ('opportunity-community-workshop-insight', 'opportunity-community-workshop', 'Nuevas preguntas', 30, 0, 1, 1, 'Las dudas del público revelan necesidades no atendidas.'),
  ('opportunity-community-sponsor-leads', 'opportunity-community-sponsor', 'Audiencia relevante', 55, 1500, 2, 0, 'La presencia de marca genera contactos con buen encaje.'),
  ('opportunity-community-sponsor-logo', 'opportunity-community-sponsor', 'Solo aparece el logo', 45, -500, 0, 0, 'Visibilidad sin participación difícilmente crea confianza.'),
  ('crisis-competitor-listen-loyal', 'crisis-competitor-listen', 'Valor diferencial', 70, 0, 1, 1, 'Los clientes explican por qué permanecen y qué sí importa mejorar.'),
  ('crisis-competitor-listen-gap', 'crisis-competitor-listen', 'Brecha real', 30, 0, -1, 1, 'La comparación revela una debilidad concreta que atender.'),
  ('crisis-competitor-copy-parity', 'crisis-competitor-copy', 'Paridad rápida', 40, 500, 0, 1, 'La entrega reduce una objeción urgente.'),
  ('crisis-competitor-copy-chase', 'crisis-competitor-copy', 'Producto reactivo', 60, -500, -1, 0, 'Perseguir al rival distrae de la propuesta propia.'),
  ('crisis-outage-communicate-trust', 'crisis-outage-communicate', 'Transparencia valorada', 65, 0, 1, 1, 'La respuesta clara demuestra responsabilidad.'),
  ('crisis-outage-communicate-churn', 'crisis-outage-communicate', 'Cliente impaciente', 35, -500, -1, 0, 'Un cliente se va, pero el resto recibe información honesta.'),
  ('crisis-outage-redundancy-stable', 'crisis-outage-redundancy', 'Servicio fortalecido', 75, 500, 1, 1, 'La inversión reduce el riesgo de repetir la falla.'),
  ('crisis-outage-redundancy-complex', 'crisis-outage-redundancy', 'Configuración compleja', 25, -500, 0, 1, 'La solución agrega aprendizaje y también costo operativo.'),
  ('crisis-cashflow-negotiate-first', 'crisis-cashflow-negotiate', 'Abono inmediato', 60, 1000, 0, 0, 'Un acuerdo concreto recupera parte del efectivo y preserva la relación.'),
  ('crisis-cashflow-negotiate-delay', 'crisis-cashflow-negotiate', 'Nueva promesa', 40, -500, 0, 0, 'La demora muestra que deben ajustarse las condiciones futuras.'),
  ('crisis-cashflow-credit-bridge', 'crisis-cashflow-credit', 'Operación protegida', 65, 2000, 0, 0, 'El puente evita detener trabajo mientras llega el cobro.'),
  ('crisis-cashflow-credit-cost', 'crisis-cashflow-credit', 'Intereses acumulados', 35, 500, -1, 0, 'Resolver liquidez con deuda añade presión y exige mejor previsión.'),
  ('crisis-review-respond-recovery', 'crisis-review-respond', 'Cliente recuperado', 70, 0, 1, 0, 'La atención rápida convierte una falla en evidencia de compromiso.'),
  ('crisis-review-respond-pileon', 'crisis-review-respond', 'Más casos aparecen', 30, -500, -1, 1, 'La conversación revela un patrón que el equipo debe corregir.'),
  ('crisis-review-campaign-proof', 'crisis-review-campaign', 'Historias positivas', 45, 500, 2, 0, 'Clientes satisfechos aportan evidencia equilibrada.'),
  ('crisis-review-campaign-backfire', 'crisis-review-campaign', 'Respuesta percibida como evasiva', 55, -500, -1, 0, 'Promocionar sin resolver la causa reduce la credibilidad.'),
  ('crisis-supplier-negotiate-discount', 'crisis-supplier-negotiate', 'Acuerdo razonable', 55, 500, 0, 0, 'La información permite ajustar el contrato sin interrumpir el servicio.'),
  ('crisis-supplier-negotiate-no', 'crisis-supplier-negotiate', 'Condiciones firmes', 45, -500, 0, 1, 'La negativa impulsa la búsqueda de una arquitectura menos dependiente.'),
  ('crisis-supplier-migrate-control', 'crisis-supplier-migrate', 'Más control', 55, 500, 0, 2, 'La migración reduce costos futuros y concentra conocimiento.'),
  ('crisis-supplier-migrate-disruption', 'crisis-supplier-migrate', 'Transición difícil', 45, -500, -1, 1, 'Cambiar bajo presión expone dependencias que no estaban documentadas.'),
  ('crisis-team-prioritize-focus', 'crisis-team-prioritize', 'Foco recuperado', 75, 0, 1, 1, 'Terminar menos cosas importantes mejora calidad y ánimo.'),
  ('crisis-team-prioritize-delay', 'crisis-team-prioritize', 'Cliente inconforme', 25, -500, -1, 0, 'Negociar una entrega cuesta reputación, pero evita una falla mayor.'),
  ('crisis-team-overtime-delivery', 'crisis-team-overtime', 'Entrega cumplida', 50, 1000, 1, 0, 'El esfuerzo puntual protege un compromiso crítico.'),
  ('crisis-team-overtime-burnout', 'crisis-team-overtime', 'Agotamiento', 50, -500, -1, -1, 'La presión sostenida reduce creatividad y aumenta errores.')
on conflict (id) do update set
  option_id = excluded.option_id,
  label = excluded.label,
  probability = excluded.probability,
  capital_delta = excluded.capital_delta,
  reputation_delta = excluded.reputation_delta,
  innovation_delta = excluded.innovation_delta,
  explanation = excluded.explanation;

insert into public.board_spaces (position, stage, category, card_id) values
  (0, 'idea'::public.board_stage, null, null),
  (1, 'validation'::public.board_stage, 'decision'::public.card_category, 'decision-focus'),
  (2, 'validation'::public.board_stage, 'innovation'::public.card_category, 'innovation-prototype'),
  (3, 'validation'::public.board_stage, 'opportunity'::public.card_category, 'opportunity-fair'),
  (4, 'validation'::public.board_stage, 'crisis'::public.card_category, 'crisis-competitor'),
  (5, 'validation'::public.board_stage, 'decision'::public.card_category, 'decision-pricing'),
  (6, 'validation'::public.board_stage, 'opportunity'::public.card_category, 'opportunity-mentor'),
  (7, 'validation'::public.board_stage, 'innovation'::public.card_category, 'innovation-automation'),
  (8, 'prototype'::public.board_stage, 'crisis'::public.card_category, 'crisis-outage'),
  (9, 'prototype'::public.board_stage, 'decision'::public.card_category, 'decision-partner'),
  (10, 'prototype'::public.board_stage, 'innovation'::public.card_category, 'innovation-patent'),
  (11, 'prototype'::public.board_stage, 'opportunity'::public.card_category, 'opportunity-grant'),
  (12, 'prototype'::public.board_stage, 'crisis'::public.card_category, 'crisis-cashflow'),
  (13, 'prototype'::public.board_stage, 'decision'::public.card_category, 'decision-investor'),
  (14, 'prototype'::public.board_stage, 'opportunity'::public.card_category, 'opportunity-referral'),
  (15, 'launch'::public.board_stage, 'innovation'::public.card_category, 'innovation-data'),
  (16, 'launch'::public.board_stage, 'crisis'::public.card_category, 'crisis-review'),
  (17, 'launch'::public.board_stage, 'decision'::public.card_category, 'decision-build-buy'),
  (18, 'launch'::public.board_stage, 'opportunity'::public.card_category, 'opportunity-corporate'),
  (19, 'launch'::public.board_stage, 'innovation'::public.card_category, 'innovation-accessibility'),
  (20, 'launch'::public.board_stage, 'crisis'::public.card_category, 'crisis-supplier'),
  (21, 'launch'::public.board_stage, 'decision'::public.card_category, 'decision-hire'),
  (22, 'growth'::public.board_stage, 'innovation'::public.card_category, 'innovation-pivot'),
  (23, 'growth'::public.board_stage, 'opportunity'::public.card_category, 'opportunity-community'),
  (24, 'growth'::public.board_stage, 'crisis'::public.card_category, 'crisis-team'),
  (25, 'growth'::public.board_stage, 'decision'::public.card_category, 'decision-focus'),
  (26, 'growth'::public.board_stage, 'opportunity'::public.card_category, 'opportunity-fair'),
  (27, 'growth'::public.board_stage, 'innovation'::public.card_category, 'innovation-prototype'),
  (28, 'growth'::public.board_stage, 'crisis'::public.card_category, 'crisis-competitor'),
  (29, 'growth'::public.board_stage, 'decision'::public.card_category, 'decision-pricing'),
  (30, 'company'::public.board_stage, null, null)
on conflict (position) do update set
  stage = excluded.stage,
  category = excluded.category,
  card_id = excluded.card_id;

insert into public.management_actions (
  id, label, cost_capital, cost_reputation, cost_innovation, capital_delta,
  reputation_delta, innovation_delta, explanation
) values
  ('financing', 'Buscar financiamiento', 0, 0, 0, 2000, 0, 0, 'El financiamiento aporta capital para seguir operando, pero no sustituye los recursos necesarios para consolidar.'),
  ('product_improvement', 'Mejorar el producto', 1000, 0, 0, 0, 0, 1, 'Reinvertir en el producto transforma capital disponible en capacidad de innovación.'),
  ('brand_building', 'Fortalecer la marca', 1000, 0, 0, 0, 1, 0, 'Una inversión de marca coherente aumenta la confianza y la reputación del emprendimiento.')
on conflict (id) do update set
  label = excluded.label,
  cost_capital = excluded.cost_capital,
  cost_reputation = excluded.cost_reputation,
  cost_innovation = excluded.cost_innovation,
  capital_delta = excluded.capital_delta,
  reputation_delta = excluded.reputation_delta,
  innovation_delta = excluded.innovation_delta,
  explanation = excluded.explanation;
